### PR TITLE
LPS-61539 Add unit test

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @fernandosouza,

I need a little help on https://projects.invisionapp.com/share/J64KCZM4M#/screens/108433455

cc @leoadb 

Thanks

### CODE REVIEW

**Comment by fernandosouza** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by marcellustavares** [comment]
@fernandosouza, please send back to me once you're done.

Thanks

**Comment by fernandosouza** [comment]
Ok, @marcellustavares

**Comment by marcellustavares** [comment]
@fernandosouza, I'll send this first batch first. I cc you on the final PR so you know when it's merged to upstream.

Thanks

**Pull request closed without merging**
